-- Create "users" table
CREATE TABLE "public"."users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "email" character varying NOT NULL,
  "password_hash" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" ("email");
-- Create "refresh_tokens" table
CREATE TABLE "public"."refresh_tokens" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "token" character varying NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "user_tokens" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "refresh_tokens_users_tokens" FOREIGN KEY ("user_tokens") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "refresh_tokens_token_key" to table: "refresh_tokens"
CREATE UNIQUE INDEX "refresh_tokens_token_key" ON "public"."refresh_tokens" ("token");
